# https://hub.docker.com/_/node
---
version: "3.8"

services:
  fach:
    image: node:18-alpine
    container_name: fachinformatiker-azubi-de
    restart: unless-stopped
    working_dir: /app
    command: npm run serve
    volumes:
      - ./:/app
    ports:
      - 3000:3000
      #     environment:
      # - NODE_ENV=production
# printenv
# echo $HOME
