# https://hub.docker.com/_/node
---
version: "3.8"

services:
  fach:
    image: node:18-alpine
    container_name: fachinformatiker-azubi-de
    restart: unless-stopped
    working_dir: /app
    command: npm run serve
    volumes:
      - ./:/app
    labels:
      traefik.enable: true

      # www
      traefik.http.routers.www_fachinformatiker.entrypoints: https
      traefik.http.routers.www_fachinformatiker.rule: Host(`www.fachinformatiker-azubi.de`)
      traefik.http.routers.www_fachinformatiker.tls: true
      traefik.http.routers.www_fachinformatiker.tls.certresolver: lets
      traefik.http.routers.www_fachinformatiker.middlewares: wwwtohttps

      # non-www
      traefik.http.routers.fachinformatiker.entrypoints: https
      traefik.http.routers.fachinformatiker.rule: Host(`fachinformatiker-azubi.de`)
      traefik.http.routers.fachinformatiker.tls: true
      traefik.http.routers.fachinformatiker.tls.certresolver: lets
    networks:
      - traefik_proxy

networks:
  traefik_proxy:
      name: traefik_proxy
      external: true
