name: Übertrage Dateien

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Zeige alle Dateien an
        run: ls -la

      - name: Komprimiere Dateien ohne .git und .github verzeichnis
        run: tar cfv files.tar --exclude=".git" --exclude=".github" .

      - name: Übertrage Dateien
        uses: appleboy/scp-action@v0.1.4
        with:
          host: 116.203.253.115
          username: git
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: files.tar
          target: /opt/

      - name: SSH in den Remote-Server
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: 116.203.253.115
          username: git
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /opt/site-alcodo
            tar xfv files.tar
            docker-compose build
            docker-compose up -d
