name: Test to create archive

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - run: echo hello > world.txt

      - uses: actions/upload-artifact@v3
        with:
          name: my-artifact
          path: world.txt

      - uses: actions/download-artifact@v3
        with:
          name: my-artifact
          path: distfiles

      - name: Übertrage Dateien
        uses: appleboy/scp-action@v0.1.4
        with:
          host: 116.203.253.115
          username: git
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: distfiles/*
          target: /opt/site-alcodo

      - name: SSH in den Remote-Server
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: 116.203.253.115
          username: git
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /opt/site-alcodo
            docker-compose build
            docker-compose up -d
